[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "azure-ai-projects>=2.5.0",
    "azure-identity>=1.25.3",
    "boto3>=1.40.0",
    "langchain>=1.0.0",
    "langchain-aws>=1.0.0",
    "langchain-chroma>=1.0.0",
    "langchain-openai>=1.0.0",
    "openai>=3.6.0",
    "pandas>=2.2.0",
    "python-dotenv>=1.1.0",
]

[project.scripts]
agent = "agent.main:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
